INSERT INTO TB_SEGMENTO (ID_SEGMENTO, NOME_SEGMENTO, ID_BOT) VALUES (SEGMENTO_SEQ.NEXTVAL, 'cuidados medicos', 1);
INSERT INTO TB_SEGMENTO (ID_SEGMENTO, NOME_SEGMENTO, ID_BOT) VALUES (SEGMENTO_SEQ.NEXTVAL, 'higiene', 2);
INSERT INTO TB_SEGMENTO (ID_SEGMENTO, NOME_SEGMENTO, ID_BOT) VALUES (SEGMENTO_SEQ.NEXTVAL, 'qualidade de vida', 3);


INSERT INTO TB_BOT (ID_BOT, NOME_BOT, MSG_INICIAL, MSG_FINAL, INATIVO, MSG_PADRAO) VALUES (BOT_SEQ.NEXTVAL, 'Nome do Bot 1', 'Mensagem inicial 1', 'Mensagem final 1', 5, 'Mensagem padrao 1');
INSERT INTO TB_BOT (ID_BOT, NOME_BOT, MSG_INICIAL, MSG_FINAL, INATIVO, MSG_PADRAO) VALUES (BOT_SEQ.NEXTVAL, 'Nome do Bot 2', 'Mensagem inicial 2', 'Mensagem final 2', 10, 'Mensagem padrao 2');
INSERT INTO TB_BOT (ID_BOT, NOME_BOT, MSG_INICIAL, MSG_FINAL, INATIVO, MSG_PADRAO) VALUES (BOT_SEQ.NEXTVAL, 'Nome do Bot 3', 'Mensagem inicial 3', 'Mensagem final 3', 15, 'Mensagem padrao 3');
